window.grammarTrainerConfig = {
  activeIds: [
    "nature:nom",
    "nature:groupe-nominal",
    "nature:verbe",
    "nature:adjectif",
    "nature:adverbe",
    "nature:pronom",
    "nature:determinant",
    "nature:conjonction-coordination",
    "fonction:proposition",
    "fonction:cod",
    "fonction:coi",
    "fonction:sujet",
    "fonction:verbe-conjugue",
    "fonction:attribut-sujet",
    "fonction:adjectif-epithete",
    "fonction:complement-verbe",
    "fonction:cc-temps",
    "fonction:cc-lieu",
    "fonction:cc-maniere",
    "fonction:complement-nom",
  ],
};
